### ISSUE TITLE
Train Code

### ISSUE THREAD

**Issue by TryHard-LL** [ms-dot-k/Multi-head-Visual-Audio-Memory#1]
Hi，thanks for your effective work. Can you provide the training code?
Thanks again.

**Comment by ms-dot-k** [comment]
The training code for LRW dataset will be released in one to two weeks. Thank you.

**Comment by TryHard-LL** [comment]
Thank for your reply. I'm waiting for you~

**Comment by ms-dot-k** [comment]
The training code was updated. Let me know if there is any problem.
