### ISSUE TITLE
LRW-1000 전처리에 대하여 질문 드립니다.

### ISSUE THREAD

**Issue by Leebh-kor** [ms-dot-k/Multi-head-Visual-Audio-Memory#3]
안녕하세요!
먼저 진행하신 연구에 대한 코드를 공개해주셔서 감사합니다.
혹시 LRW-1000에 대한 전처리코드나 dataloader코드는 따로 공개를 안하시나요??

**Comment by ms-dot-k** [comment]
안녕하세요. 
LRW-1000에 대한 dataloader코드를 아래 위치에 업로드하였습니다.
'src/data/vid_aud_lrw1000.py'
LRW-1000 같은 경우 각 비디오 마다 length가 다르므로 prediction시 (temporal average pooling) 실제 비디오 길이에 대해서만 진행하셔야합니다.
따라서 기존 LRW 기반의 모델, 학습 코드를 일부 수정하셔야합니다.
