### ISSUE TITLE
문장에 대한 train code가 궁금합니다.

### ISSUE THREAD

**Issue by saeu5407** [ms-dot-k/Multi-head-Visual-Audio-Memory#6]
안녕하세요. 제공해주신 논문과 코드를 잘 읽어보았습니다.
훌륭한 자료를 제공해주셔서 감사합니다.

다만 제공되어 있는 train.py 코드는 단어 단위의 학습에 사용된 코드로 보이는데요.
LRS 데이터에 사용한 문장 단위의 학습 코드를 공개해주실 수 있을까요?

문장 단위가 어떻게 학습되어지는지 궁금합니다.

감사합니다!

**Comment by ms-dot-k** [comment]
안녕하세요. 
본 논문에 해당하는 문장 학습 코드는 따로 공개 계획이 없습니다.

관련된 공개 되어있는 학습 코드를 참조 하셔야할 것 같습니다.
https://github.com/ms-dot-k/AVSR
https://github.com/mpc001/auto_avsr
